# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hungai Amuhinda 
description: > # this means to ignore newlines until "baseurl:"
  Hungai Amuhinda's Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hungaikev.in" # the base hostname & protocol for your site
twitter_username: hungai
github_username:  hungaikev
permalink: none
author: Hungai Amuhinda

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown

sass:
  sass_dir: css
