# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hungai Amuhinda 
description: > # this means to ignore newlines until "baseurl:"
  Hungai Amuhinda's Website | Software Engineer, Data Engineer, Engineering Manager, Site Reliability Engineer, DevOps Engineer, Cloud Engineer, and all things in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hungaikev.in" # the base hostname & protocol for your site
twitter_username: hungai
github_username:  hungaikev
linkedin_username: hungai-amuhinda
permalink: none
author: Hungai Amuhinda

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-analytics

# Build settings
markdown: kramdown

sass:
  sass_dir: css


tag_page_layout: tag_page
tag_page_dir: tag